#!/bin/sh
#set -x
if [ $# -ne 5 ];then 
  echo 'Usage: otmtest v w x y z  where v=Severity($3) w=Errorcode($5), x=Otmaagent($9)  
        y=Error-Description("$12 $13 $14") z=alarmgeneratedtime($2)'
else
 


################################
PATH=$PATH:/usr/bin:/usr/sbin
INPUT=/var/opt/OV/share/script/input
FILENAME="fileotm"
RESOLVE="ResolveIP"
EMAIL="Email"
GREP="/usr/xpg4/bin/grep"

##################################
ERR_CODE=$2
OAGT=$3
ISODATA=$4
ALARM_TIME=$5

#################################################################################
# IP to Hostname Resolution
#################################################################################

#HOST="`cat $INPUT/$RESOLVE|$GREP "$OAGT"|awk -F, '{ print $2 }'`"


#################################################################################
# Check the Description for the corresponding Error Code in the Knowledge Base #
#################################################################################
 
DES="`cat $INPUT/$FILENAME|$GREP -w $ERR_CODE|awk -F: '{ print $2 }'`"
echo "${DES}"

###############################################################################
#  Check the Severity based on the Error Code from the Knowledge Base
###############################################################################

SEV="`cat $INPUT/$FILENAME|$GREP -w $ERR_CODE|awk -F: '{ print $3 }'`"
echo "${SEV}"

#if [ "$SEV" = "" ] 
#then
#   SEV=$1
#fi

########################################################################
### If the Severity is Critical or Major send an Email
### Otherwise Log the message in the /tmp/otmlog.log
# Usage: otmtest v w x y z  where v=Severity($3) w=Errorcode($5), x=Otmaagent($9) 
#        y=Error-Description("$12 $13 $14") z=alarmgeneratedtime($2)
########################################################################

case "${SEV}" in

"Critical"|"Major")
echo "Alarm Generated from ${HOST} :    \n\
      
      SEVERITY:       ${SEV}            \n\
      ERRORCODE:      ${ERR_CODE}       \n\
      TIME     :      ${ALARM_TIME}     \n\
      OPERATORDATA:   ${ISODATA}        \n\
      ERRORDESCRPTION: ${DES}" | mailx -s "3@,@AIRKARBLRMER01" $EMAIL
      ;;
"Minor"|"Info"|"Warning")
echo "Alarm Generated from ${HOST} :    \n\

      SEVERITY:       ${SEV}            \n\
      ERRORCODE:      ${ERR_CODE}       \n\
      TIME     :      ${ALARM_TIME}     \n\
      OPERATORDATA:   ${ISODATA}        \n\
      ERRORDESCRPTION: ${DES}" >>/tmp/otmlog.log
      ;;
esac
fi
